apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: basic-demo-app
  name: basic-demo-app
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: basic-demo-app
  template:
    metadata:
      labels:
        app: basic-demo-app
    spec:
      containers:
        - name: basic-demo-app
          image: "{{ .Values.global.repository }}/bigid-basic-demo-app:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /manifest
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /manifest
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 60
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 6Gi
              cpu: 2
      imagePullSecrets:
        - name: registrypullsecret
      restartPolicy: Always