apiVersion: v1
kind: Service
metadata:
  labels:
    app: basic-demo-app
  name: bigid-basic-java-app
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 8083
      targetPort: 8083
      name: http
  selector:
    app: basic-demo-app